<?php
include 'MySQLDAO.php';
include 'Security.php';

/**
 * Definition of Class Tb_cidade
 * This class represents a data access object for a database table, it has been automatically
 * generated by Eclipse PHP Class Generator plug-in [https://sourceforge.net/projects/phpclgenerator/]
 * Template name: PHP class generator default template
 * Template filename: /ch/sahits/phpclassgenerator/templates/defaultTemplate.xml
 * Template version: 1.0
 */
class Tb_cidade {

private $dao = null;
private $i = 1;
private $tbCidadeId  = 0;
private $tbCidadePais;
private $tbCidadeNome;


/**
 * Retrieves the value from the field tb_cidade_id
 * @return String with the value of the field
 */
public function getTbCidadeId(){
	return $this->tbCidadeId;
}

/**
 * Retrieves the value from the field tb_cidade_pais
 * @return String with the value of the field
 */
public function getTbCidadePais(){
	return $this->tbCidadePais;
}

/**
 * Retrieves the value from the field tb_cidade_nome
 * @return String with the value of the field
 */
public function getTbCidadeNome(){
	return $this->tbCidadeNome;
}

/**
 * Set the value from the field tb_cidade_id
 * @param tbCidadeId String with the value for the field
 */
public function setTbCidadeId($tbCidadeId){
	$this->tbCidadeId = $tbCidadeId;
}

/**
 * Set the value from the field tb_cidade_pais
 * @param tbCidadePais String with the value for the field
 */
public function setTbCidadePais($tbCidadePais){
	$this->tbCidadePais = $tbCidadePais;
}

/**
 * Set the value from the field tb_cidade_nome
 * @param tbCidadeNome String with the value for the field
 */
public function setTbCidadeNome($tbCidadeNome){
	$this->tbCidadeNome = $tbCidadeNome;
}

/**
 * Default constructor
 * @param value some value
 */
function __construct($value){

		$this->dao = new MySQLDao("tb_cidade");
		
}

/**
 * Initialize the business object with data read from the DB.
 * @param row array containing one read record.
 */
private function init($row){
	$this->tbCidadeId = $row['tb_cidade_id'];
	$this->tbCidadePais = $row['tb_cidade_pais'];
	$this->tbCidadeNome = $row['tb_cidade_nome'];
}

/**
 * Returns the string representation of this obbject
 * @return String repesentation ofTb_cidade
 */
public function toString(){
	$s = '';
	$s .= 'tb_cidade_id: '.$this->tbCidadeId;
	$s .= 'tb_cidade_pais: '.$this->tbCidadePais;
	$s .= 'tb_cidade_nome: '.$this->tbCidadeNome;
	return $s;
}

/**
 * Returns a HTML representation of this obbject using DIVs for formatting via css
 * @return String HTML representation of the Tb_cidade object
 */
public function toHTMLString(){
	$htmlCode = "<div class=\"tb_cidade\">\n";
	$htmlCode .= '	<div class="tb_cidade_tb_cidade_id">'.$this->tbCidadeId."</div>\n";
	$htmlCode .= '	<div class="tb_cidade_tb_cidade_pais">'.$this->tbCidadePais."</div>\n";
	$htmlCode .= '	<div class="tb_cidade_tb_cidade_nome">'.$this->tbCidadeNome."</div>\n";
	$htmlCode .= "</div>\n";
	return $htmlCode;
}


public function loadAll(){

	$tb_cidade = new Tb_cidade();
	$rows = $tb_cidade->dao->getData("");
	$tb_cidades = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_cidade();
		$d->init($rows[$index]);
		array_push($tb_cidades,$d);
	}
	return $tb_cidades;
		
}

/**
 * 
 * Load the Tb_cidade uniquely by its primary key.
 * @param tbCidadeId primary key
 * @return Instance of {@link Tb_cidade}
 */
static function loadUnique($tbCidadeId){

	$tb_cidade = new Tb_cidade();
	$rows = $tb_cidade->dao->getData("`tb_cidade_id`='$tbCidadeId'");
	$tb_cidade->init($rows[0]);
	return $tb_cidade;
  	  	
}

/**
 * 
 * Load all records of Tb_cidade uniquely by its foreign keys:
 * tb_cidade_pais
 * @param tbCidadePais foreign key
 * @return array of Instance of {@link Tb_cidade}
 */
public static function loadByFKTb_cidade_pais($tbCidadePais){

	$tb_cidade = new Tb_cidade();
	$rows = $tb_cidade->dao->getData("`tb_cidade_pais`='$tbCidadePais'");
	$tb_cidades = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_cidade();
		$d->init($rows[$index]);
		array_push($tb_cidades,$d);
	}
	return $tb_cidades;
 	  	
}

/**
 * Insert this object into the DB
 * @return new id (auto increment value) genereated
 */
private function insert(){

	$list = array("tb_cidade_id"=>$this->tbCidadeId, "tb_cidade_pais"=>$this->tbCidadePais, "tb_cidade_nome"=>$this->tbCidadeNome);
	return $this->dao->insertRecord($list);	
	
}

/**
 * Update this object into the DB
 * @return number of updated records
 */
private function update(){

	$list = array("tb_cidade_id"=>$this->tbCidadeId, "tb_cidade_pais"=>$this->tbCidadePais, "tb_cidade_nome"=>$this->tbCidadeNome);
	$where = "`tb_cidade_id`='$tbCidadeId'";
	return $this->dao->updateRecord($list,$where);	
	
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initPOST(){
	if (isset($_POST['tbCidadeId'])){
		$this->tbCidadeId = $_POST['tbCidadeId'];
	}
	if (isset($_POST['tbCidadePais'])){
		$this->tbCidadePais = $_POST['tbCidadePais'];
	}
	if (isset($_POST['tbCidadeNome'])){
		$this->tbCidadeNome = $_POST['tbCidadeNome'];
	}
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initGET(){
	if (isset($_GET['tbCidadeId'])){
		$this->tbCidadeId = $_GET['tbCidadeId'];
	}
	if (isset($_GET['tbCidadePais'])){
		$this->tbCidadePais = $_GET['tbCidadePais'];
	}
	if (isset($_GET['tbCidadeNome'])){
		$this->tbCidadeNome = $_GET['tbCidadeNome'];
	}
}
}
?>