<?php
include 'MySQLDAO.php';
include 'Security.php';

/**
 * Definition of Class Tb_escolas
 * This class represents a data access object for a database table, it has been automatically
 * generated by Eclipse PHP Class Generator plug-in [https://sourceforge.net/projects/phpclgenerator/]
 * Template name: PHP class generator default template
 * Template filename: /ch/sahits/phpclassgenerator/templates/defaultTemplate.xml
 * Template version: 1.0
 */
class Tb_escolas {

private $dao = null;
private $i = 1;
private $tbEscolasId  = 0;
private $tbEscolasNome;
private $tbEscolasCidade;
private $tbEscolasSigla;
private $tbEscolasIdusuario;
private $tbEscolasIdautor;
private $tbEscolasIdtradutor;
private $tbEscolasDtformacao;


/**
 * Retrieves the value from the field tb_escolas_id
 * @return String with the value of the field
 */
public function getTbEscolasId(){
	return $this->tbEscolasId;
}

/**
 * Retrieves the value from the field tb_escolas_nome
 * @return String with the value of the field
 */
public function getTbEscolasNome(){
	return $this->tbEscolasNome;
}

/**
 * Retrieves the value from the field tb_escolas_cidade
 * @return String with the value of the field
 */
public function getTbEscolasCidade(){
	return $this->tbEscolasCidade;
}

/**
 * Retrieves the value from the field tb_escolas_sigla
 * @return String with the value of the field
 */
public function getTbEscolasSigla(){
	return $this->tbEscolasSigla;
}

/**
 * Retrieves the value from the field tb_escolas_idusuario
 * @return String with the value of the field
 */
public function getTbEscolasIdusuario(){
	return $this->tbEscolasIdusuario;
}

/**
 * Retrieves the value from the field tb_escolas_idautor
 * @return String with the value of the field
 */
public function getTbEscolasIdautor(){
	return $this->tbEscolasIdautor;
}

/**
 * Retrieves the value from the field tb_escolas_idtradutor
 * @return String with the value of the field
 */
public function getTbEscolasIdtradutor(){
	return $this->tbEscolasIdtradutor;
}

/**
 * Retrieves the value from the field tb_escolas_dtformacao
 * @return String with the value of the field
 */
public function getTbEscolasDtformacao(){
	return $this->tbEscolasDtformacao;
}

/**
 * Set the value from the field tb_escolas_id
 * @param tbEscolasId String with the value for the field
 */
public function setTbEscolasId($tbEscolasId){
	$this->tbEscolasId = $tbEscolasId;
}

/**
 * Set the value from the field tb_escolas_nome
 * @param tbEscolasNome String with the value for the field
 */
public function setTbEscolasNome($tbEscolasNome){
	$this->tbEscolasNome = $tbEscolasNome;
}

/**
 * Set the value from the field tb_escolas_cidade
 * @param tbEscolasCidade String with the value for the field
 */
public function setTbEscolasCidade($tbEscolasCidade){
	$this->tbEscolasCidade = $tbEscolasCidade;
}

/**
 * Set the value from the field tb_escolas_sigla
 * @param tbEscolasSigla String with the value for the field
 */
public function setTbEscolasSigla($tbEscolasSigla){
	$this->tbEscolasSigla = $tbEscolasSigla;
}

/**
 * Set the value from the field tb_escolas_idusuario
 * @param tbEscolasIdusuario String with the value for the field
 */
public function setTbEscolasIdusuario($tbEscolasIdusuario){
	$this->tbEscolasIdusuario = $tbEscolasIdusuario;
}

/**
 * Set the value from the field tb_escolas_idautor
 * @param tbEscolasIdautor String with the value for the field
 */
public function setTbEscolasIdautor($tbEscolasIdautor){
	$this->tbEscolasIdautor = $tbEscolasIdautor;
}

/**
 * Set the value from the field tb_escolas_idtradutor
 * @param tbEscolasIdtradutor String with the value for the field
 */
public function setTbEscolasIdtradutor($tbEscolasIdtradutor){
	$this->tbEscolasIdtradutor = $tbEscolasIdtradutor;
}

/**
 * Set the value from the field tb_escolas_dtformacao
 * @param tbEscolasDtformacao String with the value for the field
 */
public function setTbEscolasDtformacao($tbEscolasDtformacao){
	$this->tbEscolasDtformacao = $tbEscolasDtformacao;
}

/**
 * Default constructor
 * @param value some value
 */
function __construct($value){

		$this->dao = new MySQLDao("tb_escolas");
		
}

/**
 * Initialize the business object with data read from the DB.
 * @param row array containing one read record.
 */
private function init($row){
	$this->tbEscolasId = $row['tb_escolas_id'];
	$this->tbEscolasNome = $row['tb_escolas_nome'];
	$this->tbEscolasCidade = $row['tb_escolas_cidade'];
	$this->tbEscolasSigla = $row['tb_escolas_sigla'];
	$this->tbEscolasIdusuario = $row['tb_escolas_idusuario'];
	$this->tbEscolasIdautor = $row['tb_escolas_idautor'];
	$this->tbEscolasIdtradutor = $row['tb_escolas_idtradutor'];
	$this->tbEscolasDtformacao = $row['tb_escolas_dtformacao'];
}

/**
 * Returns the string representation of this obbject
 * @return String repesentation ofTb_escolas
 */
public function toString(){
	$s = '';
	$s .= 'tb_escolas_id: '.$this->tbEscolasId;
	$s .= 'tb_escolas_nome: '.$this->tbEscolasNome;
	$s .= 'tb_escolas_cidade: '.$this->tbEscolasCidade;
	$s .= 'tb_escolas_sigla: '.$this->tbEscolasSigla;
	$s .= 'tb_escolas_idusuario: '.$this->tbEscolasIdusuario;
	$s .= 'tb_escolas_idautor: '.$this->tbEscolasIdautor;
	$s .= 'tb_escolas_idtradutor: '.$this->tbEscolasIdtradutor;
	$s .= 'tb_escolas_dtformacao: '.$this->tbEscolasDtformacao;
	return $s;
}

/**
 * Returns a HTML representation of this obbject using DIVs for formatting via css
 * @return String HTML representation of the Tb_escolas object
 */
public function toHTMLString(){
	$htmlCode = "<div class=\"tb_escolas\">\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_id">'.$this->tbEscolasId."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_nome">'.$this->tbEscolasNome."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_cidade">'.$this->tbEscolasCidade."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_sigla">'.$this->tbEscolasSigla."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_idusuario">'.$this->tbEscolasIdusuario."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_idautor">'.$this->tbEscolasIdautor."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_idtradutor">'.$this->tbEscolasIdtradutor."</div>\n";
	$htmlCode .= '	<div class="tb_escolas_tb_escolas_dtformacao">'.$this->tbEscolasDtformacao."</div>\n";
	$htmlCode .= "</div>\n";
	return $htmlCode;
}


public function loadAll(){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("");
	$tb_escolass = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_escolas();
		$d->init($rows[$index]);
		array_push($tb_escolass,$d);
	}
	return $tb_escolass;
		
}

/**
 * 
 * Load the Tb_escolas uniquely by its primary key.
 * @param tbEscolasId primary key
 * @return Instance of {@link Tb_escolas}
 */
static function loadUnique($tbEscolasId){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("`tb_escolas_id`='$tbEscolasId'");
	$tb_escolas->init($rows[0]);
	return $tb_escolas;
  	  	
}

/**
 * 
 * Load all records of Tb_escolas uniquely by its foreign keys:
 * tb_escolas_cidade
 * @param tbEscolasCidade foreign key
 * @return array of Instance of {@link Tb_escolas}
 */
public static function loadByFKTb_escolas_cidade($tbEscolasCidade){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("`tb_escolas_cidade`='$tbEscolasCidade'");
	$tb_escolass = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_escolas();
		$d->init($rows[$index]);
		array_push($tb_escolass,$d);
	}
	return $tb_escolass;
 	  	
}

/**
 * 
 * Load all records of Tb_escolas uniquely by its foreign keys:
 * tb_escolas_idusuario
 * @param tbEscolasIdusuario foreign key
 * @return array of Instance of {@link Tb_escolas}
 */
public static function loadByFKTb_escolas_idusuario($tbEscolasIdusuario){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("`tb_escolas_idusuario`='$tbEscolasIdusuario'");
	$tb_escolass = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_escolas();
		$d->init($rows[$index]);
		array_push($tb_escolass,$d);
	}
	return $tb_escolass;
 	  	
}

/**
 * 
 * Load all records of Tb_escolas uniquely by its foreign keys:
 * tb_escolas_idautor
 * @param tbEscolasIdautor foreign key
 * @return array of Instance of {@link Tb_escolas}
 */
public static function loadByFKTb_escolas_idautor($tbEscolasIdautor){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("`tb_escolas_idautor`='$tbEscolasIdautor'");
	$tb_escolass = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_escolas();
		$d->init($rows[$index]);
		array_push($tb_escolass,$d);
	}
	return $tb_escolass;
 	  	
}

/**
 * 
 * Load all records of Tb_escolas uniquely by its foreign keys:
 * tb_escolas_idtradutor
 * @param tbEscolasIdtradutor foreign key
 * @return array of Instance of {@link Tb_escolas}
 */
public static function loadByFKTb_escolas_idtradutor($tbEscolasIdtradutor){

	$tb_escolas = new Tb_escolas();
	$rows = $tb_escolas->dao->getData("`tb_escolas_idtradutor`='$tbEscolasIdtradutor'");
	$tb_escolass = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_escolas();
		$d->init($rows[$index]);
		array_push($tb_escolass,$d);
	}
	return $tb_escolass;
 	  	
}

/**
 * Insert this object into the DB
 * @return new id (auto increment value) genereated
 */
private function insert(){

	$list = array("tb_escolas_id"=>$this->tbEscolasId, "tb_escolas_nome"=>$this->tbEscolasNome, "tb_escolas_cidade"=>$this->tbEscolasCidade, "tb_escolas_sigla"=>$this->tbEscolasSigla, "tb_escolas_idusuario"=>$this->tbEscolasIdusuario, "tb_escolas_idautor"=>$this->tbEscolasIdautor, "tb_escolas_idtradutor"=>$this->tbEscolasIdtradutor, "tb_escolas_dtformacao"=>$this->tbEscolasDtformacao);
	return $this->dao->insertRecord($list);	
	
}

/**
 * Update this object into the DB
 * @return number of updated records
 */
private function update(){

	$list = array("tb_escolas_id"=>$this->tbEscolasId, "tb_escolas_nome"=>$this->tbEscolasNome, "tb_escolas_cidade"=>$this->tbEscolasCidade, "tb_escolas_sigla"=>$this->tbEscolasSigla, "tb_escolas_idusuario"=>$this->tbEscolasIdusuario, "tb_escolas_idautor"=>$this->tbEscolasIdautor, "tb_escolas_idtradutor"=>$this->tbEscolasIdtradutor, "tb_escolas_dtformacao"=>$this->tbEscolasDtformacao);
	$where = "`tb_escolas_id`='$tbEscolasId'";
	return $this->dao->updateRecord($list,$where);	
	
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initPOST(){
	if (isset($_POST['tbEscolasId'])){
		$this->tbEscolasId = $_POST['tbEscolasId'];
	}
	if (isset($_POST['tbEscolasNome'])){
		$this->tbEscolasNome = $_POST['tbEscolasNome'];
	}
	if (isset($_POST['tbEscolasCidade'])){
		$this->tbEscolasCidade = $_POST['tbEscolasCidade'];
	}
	if (isset($_POST['tbEscolasSigla'])){
		$this->tbEscolasSigla = $_POST['tbEscolasSigla'];
	}
	if (isset($_POST['tbEscolasIdusuario'])){
		$this->tbEscolasIdusuario = $_POST['tbEscolasIdusuario'];
	}
	if (isset($_POST['tbEscolasIdautor'])){
		$this->tbEscolasIdautor = $_POST['tbEscolasIdautor'];
	}
	if (isset($_POST['tbEscolasIdtradutor'])){
		$this->tbEscolasIdtradutor = $_POST['tbEscolasIdtradutor'];
	}
	if (isset($_POST['tbEscolasDtformacao'])){
		$this->tbEscolasDtformacao = $_POST['tbEscolasDtformacao'];
	}
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initGET(){
	if (isset($_GET['tbEscolasId'])){
		$this->tbEscolasId = $_GET['tbEscolasId'];
	}
	if (isset($_GET['tbEscolasNome'])){
		$this->tbEscolasNome = $_GET['tbEscolasNome'];
	}
	if (isset($_GET['tbEscolasCidade'])){
		$this->tbEscolasCidade = $_GET['tbEscolasCidade'];
	}
	if (isset($_GET['tbEscolasSigla'])){
		$this->tbEscolasSigla = $_GET['tbEscolasSigla'];
	}
	if (isset($_GET['tbEscolasIdusuario'])){
		$this->tbEscolasIdusuario = $_GET['tbEscolasIdusuario'];
	}
	if (isset($_GET['tbEscolasIdautor'])){
		$this->tbEscolasIdautor = $_GET['tbEscolasIdautor'];
	}
	if (isset($_GET['tbEscolasIdtradutor'])){
		$this->tbEscolasIdtradutor = $_GET['tbEscolasIdtradutor'];
	}
	if (isset($_GET['tbEscolasDtformacao'])){
		$this->tbEscolasDtformacao = $_GET['tbEscolasDtformacao'];
	}
}
}
?>