<?php
include 'MySQLDAO.php';
include 'Security.php';

/**
 * Definition of Class Tb_editora
 * This class represents a data access object for a database table, it has been automatically
 * generated by Eclipse PHP Class Generator plug-in [https://sourceforge.net/projects/phpclgenerator/]
 * Template name: PHP class generator default template
 * Template filename: /ch/sahits/phpclassgenerator/templates/defaultTemplate.xml
 * Template version: 1.0
 */
class Tb_editora {

private $dao = null;
private $i = 1;
private $tbEditoraId  = 0;
private $tbEditoraNome;
private $tbEditoraAnofundacao;
private $tbEditoraFundador;
private $tbEditoraPais;


/**
 * Retrieves the value from the field tb_editora_id
 * @return String with the value of the field
 */
public function getTbEditoraId(){
	return $this->tbEditoraId;
}

/**
 * Retrieves the value from the field tb_editora_nome
 * @return String with the value of the field
 */
public function getTbEditoraNome(){
	return $this->tbEditoraNome;
}

/**
 * Retrieves the value from the field tb_editora_anofundacao
 * @return String with the value of the field
 */
public function getTbEditoraAnofundacao(){
	return $this->tbEditoraAnofundacao;
}

/**
 * Retrieves the value from the field tb_editora_fundador
 * @return String with the value of the field
 */
public function getTbEditoraFundador(){
	return $this->tbEditoraFundador;
}

/**
 * Retrieves the value from the field tb_editora_pais
 * @return String with the value of the field
 */
public function getTbEditoraPais(){
	return $this->tbEditoraPais;
}

/**
 * Set the value from the field tb_editora_id
 * @param tbEditoraId String with the value for the field
 */
public function setTbEditoraId($tbEditoraId){
	$this->tbEditoraId = $tbEditoraId;
}

/**
 * Set the value from the field tb_editora_nome
 * @param tbEditoraNome String with the value for the field
 */
public function setTbEditoraNome($tbEditoraNome){
	$this->tbEditoraNome = $tbEditoraNome;
}

/**
 * Set the value from the field tb_editora_anofundacao
 * @param tbEditoraAnofundacao String with the value for the field
 */
public function setTbEditoraAnofundacao($tbEditoraAnofundacao){
	$this->tbEditoraAnofundacao = $tbEditoraAnofundacao;
}

/**
 * Set the value from the field tb_editora_fundador
 * @param tbEditoraFundador String with the value for the field
 */
public function setTbEditoraFundador($tbEditoraFundador){
	$this->tbEditoraFundador = $tbEditoraFundador;
}

/**
 * Set the value from the field tb_editora_pais
 * @param tbEditoraPais String with the value for the field
 */
public function setTbEditoraPais($tbEditoraPais){
	$this->tbEditoraPais = $tbEditoraPais;
}

/**
 * Default constructor
 * @param value some value
 */
function __construct($value){

		$this->dao = new MySQLDao("tb_editora");
		
}

/**
 * Initialize the business object with data read from the DB.
 * @param row array containing one read record.
 */
private function init($row){
	$this->tbEditoraId = $row['tb_editora_id'];
	$this->tbEditoraNome = $row['tb_editora_nome'];
	$this->tbEditoraAnofundacao = $row['tb_editora_anofundacao'];
	$this->tbEditoraFundador = $row['tb_editora_fundador'];
	$this->tbEditoraPais = $row['tb_editora_pais'];
}

/**
 * Returns the string representation of this obbject
 * @return String repesentation ofTb_editora
 */
public function toString(){
	$s = '';
	$s .= 'tb_editora_id: '.$this->tbEditoraId;
	$s .= 'tb_editora_nome: '.$this->tbEditoraNome;
	$s .= 'tb_editora_anofundacao: '.$this->tbEditoraAnofundacao;
	$s .= 'tb_editora_fundador: '.$this->tbEditoraFundador;
	$s .= 'tb_editora_pais: '.$this->tbEditoraPais;
	return $s;
}

/**
 * Returns a HTML representation of this obbject using DIVs for formatting via css
 * @return String HTML representation of the Tb_editora object
 */
public function toHTMLString(){
	$htmlCode = "<div class=\"tb_editora\">\n";
	$htmlCode .= '	<div class="tb_editora_tb_editora_id">'.$this->tbEditoraId."</div>\n";
	$htmlCode .= '	<div class="tb_editora_tb_editora_nome">'.$this->tbEditoraNome."</div>\n";
	$htmlCode .= '	<div class="tb_editora_tb_editora_anofundacao">'.$this->tbEditoraAnofundacao."</div>\n";
	$htmlCode .= '	<div class="tb_editora_tb_editora_fundador">'.$this->tbEditoraFundador."</div>\n";
	$htmlCode .= '	<div class="tb_editora_tb_editora_pais">'.$this->tbEditoraPais."</div>\n";
	$htmlCode .= "</div>\n";
	return $htmlCode;
}


public function loadAll(){

	$tb_editora = new Tb_editora();
	$rows = $tb_editora->dao->getData("");
	$tb_editoras = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_editora();
		$d->init($rows[$index]);
		array_push($tb_editoras,$d);
	}
	return $tb_editoras;
		
}

/**
 * 
 * Load the Tb_editora uniquely by its primary key.
 * @param tbEditoraId primary key
 * @return Instance of {@link Tb_editora}
 */
static function loadUnique($tbEditoraId){

	$tb_editora = new Tb_editora();
	$rows = $tb_editora->dao->getData("`tb_editora_id`='$tbEditoraId'");
	$tb_editora->init($rows[0]);
	return $tb_editora;
  	  	
}

/**
 * 
 * Load all records of Tb_editora uniquely by its foreign keys:
 * tb_editora_pais
 * @param tbEditoraPais foreign key
 * @return array of Instance of {@link Tb_editora}
 */
public static function loadByFKTb_editora_pais($tbEditoraPais){

	$tb_editora = new Tb_editora();
	$rows = $tb_editora->dao->getData("`tb_editora_pais`='$tbEditoraPais'");
	$tb_editoras = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_editora();
		$d->init($rows[$index]);
		array_push($tb_editoras,$d);
	}
	return $tb_editoras;
 	  	
}

/**
 * Insert this object into the DB
 * @return new id (auto increment value) genereated
 */
private function insert(){

	$list = array("tb_editora_id"=>$this->tbEditoraId, "tb_editora_nome"=>$this->tbEditoraNome, "tb_editora_anofundacao"=>$this->tbEditoraAnofundacao, "tb_editora_fundador"=>$this->tbEditoraFundador, "tb_editora_pais"=>$this->tbEditoraPais);
	return $this->dao->insertRecord($list);	
	
}

/**
 * Update this object into the DB
 * @return number of updated records
 */
private function update(){

	$list = array("tb_editora_id"=>$this->tbEditoraId, "tb_editora_nome"=>$this->tbEditoraNome, "tb_editora_anofundacao"=>$this->tbEditoraAnofundacao, "tb_editora_fundador"=>$this->tbEditoraFundador, "tb_editora_pais"=>$this->tbEditoraPais);
	$where = "`tb_editora_id`='$tbEditoraId'";
	return $this->dao->updateRecord($list,$where);	
	
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initPOST(){
	if (isset($_POST['tbEditoraId'])){
		$this->tbEditoraId = $_POST['tbEditoraId'];
	}
	if (isset($_POST['tbEditoraNome'])){
		$this->tbEditoraNome = $_POST['tbEditoraNome'];
	}
	if (isset($_POST['tbEditoraAnofundacao'])){
		$this->tbEditoraAnofundacao = $_POST['tbEditoraAnofundacao'];
	}
	if (isset($_POST['tbEditoraFundador'])){
		$this->tbEditoraFundador = $_POST['tbEditoraFundador'];
	}
	if (isset($_POST['tbEditoraPais'])){
		$this->tbEditoraPais = $_POST['tbEditoraPais'];
	}
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initGET(){
	if (isset($_GET['tbEditoraId'])){
		$this->tbEditoraId = $_GET['tbEditoraId'];
	}
	if (isset($_GET['tbEditoraNome'])){
		$this->tbEditoraNome = $_GET['tbEditoraNome'];
	}
	if (isset($_GET['tbEditoraAnofundacao'])){
		$this->tbEditoraAnofundacao = $_GET['tbEditoraAnofundacao'];
	}
	if (isset($_GET['tbEditoraFundador'])){
		$this->tbEditoraFundador = $_GET['tbEditoraFundador'];
	}
	if (isset($_GET['tbEditoraPais'])){
		$this->tbEditoraPais = $_GET['tbEditoraPais'];
	}
}
}
?>