<?php
include 'MySQLDAO.php';
include 'Security.php';

/**
 * Definition of Class Tb_livro_andamento
 * This class represents a data access object for a database table, it has been automatically
 * generated by Eclipse PHP Class Generator plug-in [https://sourceforge.net/projects/phpclgenerator/]
 * Template name: PHP class generator default template
 * Template filename: /ch/sahits/phpclassgenerator/templates/defaultTemplate.xml
 * Template version: 1.0
 */
class Tb_livro_andamento {

private $dao = null;
private $i = 1;
private $tbLivroAndamentoIdlivro  = 0;
private $tbLivroAndamentoIdusuario  = 0;
private $tbLivroAndamentoUltimapaginalida;
private $tbLivroAndamentoRange;
private $tbLivroAndamentoCapitulolido;
private $tbLivroAndamentoDtinicio;
private $tbLivroAndamentoDtpause;
private $tbLivroAndamentoDtfim;


/**
 * Retrieves the value from the field tb_livro_andamento_idlivro
 * @return String with the value of the field
 */
public function getTbLivroAndamentoIdlivro(){
	return $this->tbLivroAndamentoIdlivro;
}

/**
 * Retrieves the value from the field tb_livro_andamento_idusuario
 * @return String with the value of the field
 */
public function getTbLivroAndamentoIdusuario(){
	return $this->tbLivroAndamentoIdusuario;
}

/**
 * Retrieves the value from the field tb_livro_andamento_ultimaPaginaLida
 * @return String with the value of the field
 */
public function getTbLivroAndamentoUltimapaginalida(){
	return $this->tbLivroAndamentoUltimapaginalida;
}

/**
 * Retrieves the value from the field tb_livro_andamento_Range
 * @return String with the value of the field
 */
public function getTbLivroAndamentoRange(){
	return $this->tbLivroAndamentoRange;
}

/**
 * Retrieves the value from the field tb_livro_andamento_capituloLido
 * @return String with the value of the field
 */
public function getTbLivroAndamentoCapitulolido(){
	return $this->tbLivroAndamentoCapitulolido;
}

/**
 * Retrieves the value from the field tb_livro_andamento_dtinicio
 * @return String with the value of the field
 */
public function getTbLivroAndamentoDtinicio(){
	return $this->tbLivroAndamentoDtinicio;
}

/**
 * Retrieves the value from the field tb_livro_andamento_dtpause
 * @return String with the value of the field
 */
public function getTbLivroAndamentoDtpause(){
	return $this->tbLivroAndamentoDtpause;
}

/**
 * Retrieves the value from the field tb_livro_andamento_dtfim
 * @return String with the value of the field
 */
public function getTbLivroAndamentoDtfim(){
	return $this->tbLivroAndamentoDtfim;
}

/**
 * Set the value from the field tb_livro_andamento_idlivro
 * @param tbLivroAndamentoIdlivro String with the value for the field
 */
public function setTbLivroAndamentoIdlivro($tbLivroAndamentoIdlivro){
	$this->tbLivroAndamentoIdlivro = $tbLivroAndamentoIdlivro;
}

/**
 * Set the value from the field tb_livro_andamento_idusuario
 * @param tbLivroAndamentoIdusuario String with the value for the field
 */
public function setTbLivroAndamentoIdusuario($tbLivroAndamentoIdusuario){
	$this->tbLivroAndamentoIdusuario = $tbLivroAndamentoIdusuario;
}

/**
 * Set the value from the field tb_livro_andamento_ultimaPaginaLida
 * @param tbLivroAndamentoUltimapaginalida String with the value for the field
 */
public function setTbLivroAndamentoUltimapaginalida($tbLivroAndamentoUltimapaginalida){
	$this->tbLivroAndamentoUltimapaginalida = $tbLivroAndamentoUltimapaginalida;
}

/**
 * Set the value from the field tb_livro_andamento_Range
 * @param tbLivroAndamentoRange String with the value for the field
 */
public function setTbLivroAndamentoRange($tbLivroAndamentoRange){
	$this->tbLivroAndamentoRange = $tbLivroAndamentoRange;
}

/**
 * Set the value from the field tb_livro_andamento_capituloLido
 * @param tbLivroAndamentoCapitulolido String with the value for the field
 */
public function setTbLivroAndamentoCapitulolido($tbLivroAndamentoCapitulolido){
	$this->tbLivroAndamentoCapitulolido = $tbLivroAndamentoCapitulolido;
}

/**
 * Set the value from the field tb_livro_andamento_dtinicio
 * @param tbLivroAndamentoDtinicio String with the value for the field
 */
public function setTbLivroAndamentoDtinicio($tbLivroAndamentoDtinicio){
	$this->tbLivroAndamentoDtinicio = $tbLivroAndamentoDtinicio;
}

/**
 * Set the value from the field tb_livro_andamento_dtpause
 * @param tbLivroAndamentoDtpause String with the value for the field
 */
public function setTbLivroAndamentoDtpause($tbLivroAndamentoDtpause){
	$this->tbLivroAndamentoDtpause = $tbLivroAndamentoDtpause;
}

/**
 * Set the value from the field tb_livro_andamento_dtfim
 * @param tbLivroAndamentoDtfim String with the value for the field
 */
public function setTbLivroAndamentoDtfim($tbLivroAndamentoDtfim){
	$this->tbLivroAndamentoDtfim = $tbLivroAndamentoDtfim;
}

/**
 * Default constructor
 * @param value some value
 */
function __construct($value){

		$this->dao = new MySQLDao("tb_livro_andamento");
		
}

/**
 * Initialize the business object with data read from the DB.
 * @param row array containing one read record.
 */
private function init($row){
	$this->tbLivroAndamentoIdlivro = $row['tb_livro_andamento_idlivro'];
	$this->tbLivroAndamentoIdusuario = $row['tb_livro_andamento_idusuario'];
	$this->tbLivroAndamentoUltimapaginalida = $row['tb_livro_andamento_ultimaPaginaLida'];
	$this->tbLivroAndamentoRange = $row['tb_livro_andamento_Range'];
	$this->tbLivroAndamentoCapitulolido = $row['tb_livro_andamento_capituloLido'];
	$this->tbLivroAndamentoDtinicio = $row['tb_livro_andamento_dtinicio'];
	$this->tbLivroAndamentoDtpause = $row['tb_livro_andamento_dtpause'];
	$this->tbLivroAndamentoDtfim = $row['tb_livro_andamento_dtfim'];
}

/**
 * Returns the string representation of this obbject
 * @return String repesentation ofTb_livro_andamento
 */
public function toString(){
	$s = '';
	$s .= 'tb_livro_andamento_idlivro: '.$this->tbLivroAndamentoIdlivro;
	$s .= 'tb_livro_andamento_idusuario: '.$this->tbLivroAndamentoIdusuario;
	$s .= 'tb_livro_andamento_ultimaPaginaLida: '.$this->tbLivroAndamentoUltimapaginalida;
	$s .= 'tb_livro_andamento_Range: '.$this->tbLivroAndamentoRange;
	$s .= 'tb_livro_andamento_capituloLido: '.$this->tbLivroAndamentoCapitulolido;
	$s .= 'tb_livro_andamento_dtinicio: '.$this->tbLivroAndamentoDtinicio;
	$s .= 'tb_livro_andamento_dtpause: '.$this->tbLivroAndamentoDtpause;
	$s .= 'tb_livro_andamento_dtfim: '.$this->tbLivroAndamentoDtfim;
	return $s;
}

/**
 * Returns a HTML representation of this obbject using DIVs for formatting via css
 * @return String HTML representation of the Tb_livro_andamento object
 */
public function toHTMLString(){
	$htmlCode = "<div class=\"tb_livro_andamento\">\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_idlivro">'.$this->tbLivroAndamentoIdlivro."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_idusuario">'.$this->tbLivroAndamentoIdusuario."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_ultimaPaginaLida">'.$this->tbLivroAndamentoUltimapaginalida."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_Range">'.$this->tbLivroAndamentoRange."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_capituloLido">'.$this->tbLivroAndamentoCapitulolido."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_dtinicio">'.$this->tbLivroAndamentoDtinicio."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_dtpause">'.$this->tbLivroAndamentoDtpause."</div>\n";
	$htmlCode .= '	<div class="tb_livro_andamento_tb_livro_andamento_dtfim">'.$this->tbLivroAndamentoDtfim."</div>\n";
	$htmlCode .= "</div>\n";
	return $htmlCode;
}


public function loadAll(){

	$tb_livro_andamento = new Tb_livro_andamento();
	$rows = $tb_livro_andamento->dao->getData("");
	$tb_livro_andamentos = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_livro_andamento();
		$d->init($rows[$index]);
		array_push($tb_livro_andamentos,$d);
	}
	return $tb_livro_andamentos;
		
}

/**
 * 
 * Load the Tb_livro_andamento uniquely by its primary key.
 * @param tbLivroAndamentoIdlivro primary key
 * @param tbLivroAndamentoIdusuario primary key
 * @return Instance of {@link Tb_livro_andamento}
 */
static function loadUnique($tbLivroAndamentoIdlivro, $tbLivroAndamentoIdusuario){

	$tb_livro_andamento = new Tb_livro_andamento();
	$rows = $tb_livro_andamento->dao->getData("`tb_livro_andamento_idlivro`='$tbLivroAndamentoIdlivro' AND `tb_livro_andamento_idusuario`='$tbLivroAndamentoIdusuario'");
	$tb_livro_andamento->init($rows[0]);
	return $tb_livro_andamento;
  	  	
}

/**
 * 
 * Load all records of Tb_livro_andamento uniquely by its foreign keys:
 * tb_livro_andamento_idlivro
 * @param tbLivroAndamentoIdlivro foreign key
 * @return array of Instance of {@link Tb_livro_andamento}
 */
public static function loadByFKTb_livro_andamento_idlivro($tbLivroAndamentoIdlivro){

	$tb_livro_andamento = new Tb_livro_andamento();
	$rows = $tb_livro_andamento->dao->getData("`tb_livro_andamento_idlivro`='$tbLivroAndamentoIdlivro'");
	$tb_livro_andamentos = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_livro_andamento();
		$d->init($rows[$index]);
		array_push($tb_livro_andamentos,$d);
	}
	return $tb_livro_andamentos;
 	  	
}

/**
 * 
 * Load all records of Tb_livro_andamento uniquely by its foreign keys:
 * tb_livro_andamento_idusuario
 * @param tbLivroAndamentoIdusuario foreign key
 * @return array of Instance of {@link Tb_livro_andamento}
 */
public static function loadByFKTb_livro_andamento_idusuario($tbLivroAndamentoIdusuario){

	$tb_livro_andamento = new Tb_livro_andamento();
	$rows = $tb_livro_andamento->dao->getData("`tb_livro_andamento_idusuario`='$tbLivroAndamentoIdusuario'");
	$tb_livro_andamentos = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_livro_andamento();
		$d->init($rows[$index]);
		array_push($tb_livro_andamentos,$d);
	}
	return $tb_livro_andamentos;
 	  	
}

/**
 * Insert this object into the DB
 * @return new id (auto increment value) genereated
 */
private function insert(){

	$list = array("tb_livro_andamento_idlivro"=>$this->tbLivroAndamentoIdlivro, "tb_livro_andamento_idusuario"=>$this->tbLivroAndamentoIdusuario, "tb_livro_andamento_ultimaPaginaLida"=>$this->tbLivroAndamentoUltimapaginalida, "tb_livro_andamento_Range"=>$this->tbLivroAndamentoRange, "tb_livro_andamento_capituloLido"=>$this->tbLivroAndamentoCapitulolido, "tb_livro_andamento_dtinicio"=>$this->tbLivroAndamentoDtinicio, "tb_livro_andamento_dtpause"=>$this->tbLivroAndamentoDtpause, "tb_livro_andamento_dtfim"=>$this->tbLivroAndamentoDtfim);
	return $this->dao->insertRecord($list);	
	
}

/**
 * Update this object into the DB
 * @return number of updated records
 */
private function update(){

	$list = array("tb_livro_andamento_idlivro"=>$this->tbLivroAndamentoIdlivro, "tb_livro_andamento_idusuario"=>$this->tbLivroAndamentoIdusuario, "tb_livro_andamento_ultimaPaginaLida"=>$this->tbLivroAndamentoUltimapaginalida, "tb_livro_andamento_Range"=>$this->tbLivroAndamentoRange, "tb_livro_andamento_capituloLido"=>$this->tbLivroAndamentoCapitulolido, "tb_livro_andamento_dtinicio"=>$this->tbLivroAndamentoDtinicio, "tb_livro_andamento_dtpause"=>$this->tbLivroAndamentoDtpause, "tb_livro_andamento_dtfim"=>$this->tbLivroAndamentoDtfim);
	$where = "`tb_livro_andamento_idlivro`='$tbLivroAndamentoIdlivro' AND `tb_livro_andamento_idusuario`='$tbLivroAndamentoIdusuario'";
	return $this->dao->updateRecord($list,$where);	
	
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initPOST(){
	if (isset($_POST['tbLivroAndamentoIdlivro'])){
		$this->tbLivroAndamentoIdlivro = $_POST['tbLivroAndamentoIdlivro'];
	}
	if (isset($_POST['tbLivroAndamentoIdusuario'])){
		$this->tbLivroAndamentoIdusuario = $_POST['tbLivroAndamentoIdusuario'];
	}
	if (isset($_POST['tbLivroAndamentoUltimapaginalida'])){
		$this->tbLivroAndamentoUltimapaginalida = $_POST['tbLivroAndamentoUltimapaginalida'];
	}
	if (isset($_POST['tbLivroAndamentoRange'])){
		$this->tbLivroAndamentoRange = $_POST['tbLivroAndamentoRange'];
	}
	if (isset($_POST['tbLivroAndamentoCapitulolido'])){
		$this->tbLivroAndamentoCapitulolido = $_POST['tbLivroAndamentoCapitulolido'];
	}
	if (isset($_POST['tbLivroAndamentoDtinicio'])){
		$this->tbLivroAndamentoDtinicio = $_POST['tbLivroAndamentoDtinicio'];
	}
	if (isset($_POST['tbLivroAndamentoDtpause'])){
		$this->tbLivroAndamentoDtpause = $_POST['tbLivroAndamentoDtpause'];
	}
	if (isset($_POST['tbLivroAndamentoDtfim'])){
		$this->tbLivroAndamentoDtfim = $_POST['tbLivroAndamentoDtfim'];
	}
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initGET(){
	if (isset($_GET['tbLivroAndamentoIdlivro'])){
		$this->tbLivroAndamentoIdlivro = $_GET['tbLivroAndamentoIdlivro'];
	}
	if (isset($_GET['tbLivroAndamentoIdusuario'])){
		$this->tbLivroAndamentoIdusuario = $_GET['tbLivroAndamentoIdusuario'];
	}
	if (isset($_GET['tbLivroAndamentoUltimapaginalida'])){
		$this->tbLivroAndamentoUltimapaginalida = $_GET['tbLivroAndamentoUltimapaginalida'];
	}
	if (isset($_GET['tbLivroAndamentoRange'])){
		$this->tbLivroAndamentoRange = $_GET['tbLivroAndamentoRange'];
	}
	if (isset($_GET['tbLivroAndamentoCapitulolido'])){
		$this->tbLivroAndamentoCapitulolido = $_GET['tbLivroAndamentoCapitulolido'];
	}
	if (isset($_GET['tbLivroAndamentoDtinicio'])){
		$this->tbLivroAndamentoDtinicio = $_GET['tbLivroAndamentoDtinicio'];
	}
	if (isset($_GET['tbLivroAndamentoDtpause'])){
		$this->tbLivroAndamentoDtpause = $_GET['tbLivroAndamentoDtpause'];
	}
	if (isset($_GET['tbLivroAndamentoDtfim'])){
		$this->tbLivroAndamentoDtfim = $_GET['tbLivroAndamentoDtfim'];
	}
}
}
?>