<?php
include 'MySQLDAO.php';
include 'Security.php';

/**
 * Definition of Class Tb_pais
 * This class represents a data access object for a database table, it has been automatically
 * generated by Eclipse PHP Class Generator plug-in [https://sourceforge.net/projects/phpclgenerator/]
 * Template name: PHP class generator default template
 * Template filename: /ch/sahits/phpclassgenerator/templates/defaultTemplate.xml
 * Template version: 1.0
 */
class Tb_pais {

private $dao = null;
private $i = 1;
private $tbPaisId  = 0;
private $tbPaisNome;


/**
 * Retrieves the value from the field tb_pais_id
 * @return String with the value of the field
 */
public function getTbPaisId(){
	return $this->tbPaisId;
}

/**
 * Retrieves the value from the field tb_pais_nome
 * @return String with the value of the field
 */
public function getTbPaisNome(){
	return $this->tbPaisNome;
}

/**
 * Set the value from the field tb_pais_id
 * @param tbPaisId String with the value for the field
 */
public function setTbPaisId($tbPaisId){
	$this->tbPaisId = $tbPaisId;
}

/**
 * Set the value from the field tb_pais_nome
 * @param tbPaisNome String with the value for the field
 */
public function setTbPaisNome($tbPaisNome){
	$this->tbPaisNome = $tbPaisNome;
}

/**
 * Default constructor
 * @param value some value
 */
function __construct($value){

		$this->dao = new MySQLDao("tb_pais");
		
}

/**
 * Initialize the business object with data read from the DB.
 * @param row array containing one read record.
 */
private function init($row){
	$this->tbPaisId = $row['tb_pais_id'];
	$this->tbPaisNome = $row['tb_pais_nome'];
}

/**
 * Returns the string representation of this obbject
 * @return String repesentation ofTb_pais
 */
public function toString(){
	$s = '';
	$s .= 'tb_pais_id: '.$this->tbPaisId;
	$s .= 'tb_pais_nome: '.$this->tbPaisNome;
	return $s;
}

/**
 * Returns a HTML representation of this obbject using DIVs for formatting via css
 * @return String HTML representation of the Tb_pais object
 */
public function toHTMLString(){
	$htmlCode = "<div class=\"tb_pais\">\n";
	$htmlCode .= '	<div class="tb_pais_tb_pais_id">'.$this->tbPaisId."</div>\n";
	$htmlCode .= '	<div class="tb_pais_tb_pais_nome">'.$this->tbPaisNome."</div>\n";
	$htmlCode .= "</div>\n";
	return $htmlCode;
}


public function loadAll(){

	$tb_pais = new Tb_pais();
	$rows = $tb_pais->dao->getData("");
	$tb_paiss = array();
	for ($index = 0; $index < sizeof($rows); $index++) {
		$d = new Tb_pais();
		$d->init($rows[$index]);
		array_push($tb_paiss,$d);
	}
	return $tb_paiss;
		
}

/**
 * 
 * Load the Tb_pais uniquely by its primary key.
 * @param tbPaisId primary key
 * @return Instance of {@link Tb_pais}
 */
static function loadUnique($tbPaisId){

	$tb_pais = new Tb_pais();
	$rows = $tb_pais->dao->getData("`tb_pais_id`='$tbPaisId'");
	$tb_pais->init($rows[0]);
	return $tb_pais;
  	  	
}

/**
 * Insert this object into the DB
 * @return new id (auto increment value) genereated
 */
private function insert(){

	$list = array("tb_pais_id"=>$this->tbPaisId, "tb_pais_nome"=>$this->tbPaisNome);
	return $this->dao->insertRecord($list);	
	
}

/**
 * Update this object into the DB
 * @return number of updated records
 */
private function update(){

	$list = array("tb_pais_id"=>$this->tbPaisId, "tb_pais_nome"=>$this->tbPaisNome);
	$where = "`tb_pais_id`='$tbPaisId'";
	return $this->dao->updateRecord($list,$where);	
	
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initPOST(){
	if (isset($_POST['tbPaisId'])){
		$this->tbPaisId = $_POST['tbPaisId'];
	}
	if (isset($_POST['tbPaisNome'])){
		$this->tbPaisNome = $_POST['tbPaisNome'];
	}
}

/**
 * Initialize the business object with data read from the DB.
 */
private function initGET(){
	if (isset($_GET['tbPaisId'])){
		$this->tbPaisId = $_GET['tbPaisId'];
	}
	if (isset($_GET['tbPaisNome'])){
		$this->tbPaisNome = $_GET['tbPaisNome'];
	}
}
}
?>